### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Sunekaer** [gigaherz/ToolBelt#38] opened 2019-08-06 17:36 UTC
[Crash log](https://s1.sunekaer.com/files/crash-2019-08-06_19.35.02-client.txt)

forge:28.0.45
ToolBelt-1.14.4-1.10.0.jar

**Comment by gigaherz** [comment] 2019-08-06 21:11
At a glance, it seems you have Random Patches in there. It seems there's some issue between randompatches and the latest version of forge, so I'm closing this as "not my fault", unless you can show that it still crashes without that coremod.

**Comment by Sunekaer** [comment] 2019-08-07 16:15
I removed Random Patches and still get a crash 
https://s1.sunekaer.com/files/crash-2019-08-07_18.13.24-client.txt

**Comment by gigaherz** [comment] 2019-08-07 17:16
Okay reopened while I investigate. I still suspect it's not really my mod's fault, but I'll do some extra testing to confirm.

**Comment by CobaltL** [comment] 2019-08-08 14:40
[Crash Log](https://github.com/gigaherz/ToolBelt/files/3482250/crash-2019-08-08_22.29.08-client.txt)
Somehow, removing your mod makes the game not crash, but using your mod alone is still perfectly fine. Could you please help me take a look at what's going on?

**Comment by gigaherz** [comment] 2019-08-08 14:56
My only guess is that SOMETHING is causing the `InputEvent.KeyInputEvent` handler to trigger before `initKeybinds()` of my mod has run. I could add a workaround, a null-check in that event. But if initKeybinds never runs, then that would mean the keybinds are NOT set up at the right time.

If you have the time, the best way to find the culprit, would be to bisect the mod list
take away half of the mods, if it stops crashing, then the issue is in THAT half that you took out. If it keeps crashing then the issue is in the half that remained.
Keep the half that was crashing (aka, swap the two halves if it kept working), and repeat the operation removing another half (so you'd have only one quarter left). You can keep doing that until only 1 mod remains, where if you remove that mod, the issue is fixed, and if you leave it, it remains crashing.

**Comment by gigaherz** [comment] 2019-08-08 18:09
Can anyone provide a full log, from start to crash, instead of only the crash log? In the vanilla launcher, that might require telling the launcher to open the log window on start, and then copying from there.

**Comment by Sunekaer** [comment] 2019-08-08 19:03
https://paste.feed-the-beast.com/view/f313eaf8

**Comment by gigaherz** [comment] 2019-08-08 19:19
AHA!
```
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent
```
There was an exception constructing one of the mods because of the breaking change in forge 28.0.45. I can't tell you which mod, but one of them is using the old package name for TickEvent.*

**Comment by ProsperCraft** [comment] 2019-08-08 19:31
I just put an update freeze on my pack until JEI updates after forge fixes JEI's issue they posted, no point until then, by then several more mods will have updated and will start testing again.

**Closed** 2019-09-15 22:03 UTC
