### ISSUE TITLE
[Suggestion] Auto select tool based on block you are looking at

### ISSUE THREAD

**Issue by Shovinus** [gigaherz/ToolBelt#23] opened 2018-10-26 21:45 UTC
There is another mod that does this but their tool belt is worse, so this would be a really cool addition, just have a key bind that automatically tries to pick the right tool for the block, possibly you could even add gui so you can set for the main types which tool should be chosen, for those situations where you carry around a silk touch and a fortune tool and want silk to be the one chosen first.

**Comment by gigaherz** [comment] 2018-10-26 23:17
Duplicate of #19
I'm currently not interested in implementing such a feature, but I'm keeping it in mind.

**Closed by gigaherz** 2018-10-26 23:17 UTC

**Comment by Shovinus** [comment] 2018-10-26 23:18
Ah sorry I did a search for auto and change and found nothing.
