### ISSUE TITLE
GL ERROR Log spam while radial menu is open

### ISSUE THREAD

**Issue by Revvilo** [gigaherz/ToolBelt#42] opened 2019-08-21 09:37 UTC
Pretty simple; the console is spammed with the below message (every frame, from what I can tell) while R is being held to open the toolbelt menu.

```
[21:21:41] [Client thread/ERROR]: ########## GL ERROR ##########
[21:21:41] [Client thread/ERROR]: @ Render
[21:21:41] [Client thread/ERROR]: 65539: Invalid key -1
```

#### Versions

| Name | Version |
| -- | -- |
| Minecraft | 1.14.4 |
| Forge | 28.0.55 |
| ToolBelt | 1.11.0 |

**Comment by gigaherz** [comment] 2019-08-21 20:50
I'll take a look, but I don't recall it happening in my development environment. Just in case, what OS/GPU/Driver version?

**Comment by Revvilo** [comment] 2019-08-21 23:00
Yeah, it could be to do with other mods, too. I'll test if that is the case if you can't reproduce it.
OS is Windows 10 Pro v1803
GPU is Gigabyte GTX 1060 with Driver 431.60

**Comment by RobertSkalko** [comment] 2019-10-12 13:21
did you solve this? I seem to have gotten a similar report here https://github.com/RobertSkalko/Mine-and-Slash/issues/95

**Comment by gigaherz** [comment] 2019-10-12 13:38
I have not been able to reproduce this.

**Comment by TheCallunxz** [comment] 2019-10-12 14:52
I just found the issue:
`new KeyBinding("key.toolbelt.cycle.left", -1, "key.toolbelt.category"));`
This line is causing the error. Setting the keybinding to -1 seems to cause the GL error.

**Comment by gigaherz** [comment] 2019-10-12 14:55
Huh.... Did I not change that already...? Maybe I never pushed a fix...

**Comment by gigaherz** [comment] 2020-03-11 14:26
v1.14.1 for 1.15.2 should fix this log spam.
Turns out GLFW in certain platforms doesn't like me calling InputMappings.isKeyDown for an unassigned keybind.

**Closed by gigaherz** 2020-03-11 14:26 UTC
