### ISSUE TITLE
Lost tools after adding pouches

### ISSUE THREAD

**Issue by Ash70** [gigaherz/ToolBelt#2] opened 2017-03-03 23:02 UTC
While having a tinker's construct hammer in the toolbelt, I added 5 upgrades (pouches) to it in an anvil. Then I opened it and added a pickaxe, an axe, an excavator and a mattock; I placed it in the bauble slot and I pressed the shortcut button to extract, to find it only contained my hammer (the one that was in there when I applied the upgrades) all the other tools vanished.

**Comment by gigaherz** [comment] 2017-04-21 09:30
Hey there, I didn't see this issue before. The issue described here should be fixed in the latest version (since v1.4.0), so I'll be closing this assuming that's the case. If you can still reproduce any item loss, feel free to reopen, or comment here and I will reopen.

**Closed by gigaherz** 2017-04-21 09:30 UTC
